config/routes.rb
Rails.application.routes.draw do
  resources :centres
  resources :users, only: [:new, :create, :edit, :update, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'centres#index'

end

app/models/centre.rb
class Centre < ActiveRecord::Base
  def self.group_by_city
    Centre.all.group_by(&:city)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  # has_many :reviews, dependent: :destroy

  validates :email,
    presence: true, 
    uniqueness: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create   

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :impersonating_user?

protected

  def restrict_admin
    redirect_to movies_path unless current_user && current_user.admin || impersonating_user?
  end

  # def restrict_access
  #   if !current_user
  #     flash[:alert] = "You must log in."
  #     redirect_to new_session_path
  #   end
  # end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def impersonating_user?
    session[:admin_session]
  end

  def authenticate_user!
    if !current_user
      redirect_to root_path, :alert => 'You Must Be Logged In'
    end
  end

end

app/controllers/centres_controller.rb
class CentresController < ApplicationController
  before_action :set_centre, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :update]

  # GET /centres
  # GET /centres.json
  def index
    @centres = Centre.all
  end

  # GET /centres/1
  # GET /centres/1.json
  def show
  end

  # GET /centres/new
  def new
    @centre = Centre.new
  end

  # GET /centres/1/edit
  def edit
  end

  # POST /centres
  # POST /centres.json
  def create
    @centre = Centre.new(centre_params)

    respond_to do |format|
      if @centre.save
        format.html { redirect_to @centre, notice: 'Centre was successfully created.' }
        format.json { render :show, status: :created, location: @centre }
      else
        format.html { render :new }
        format.json { render json: @centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centres/1
  # PATCH/PUT /centres/1.json
  def update
    respond_to do |format|
      if @centre.update(centre_params)
        format.html { redirect_to @centre, notice: 'Centre was successfully updated.' }
        format.json { render :show, status: :ok, location: @centre }
      else
        format.html { render :edit }
        format.json { render json: @centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centres/1
  # DELETE /centres/1.json
  def destroy
    @centre.destroy
    respond_to do |format|
      format.html { redirect_to centres_url, notice: 'Centre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centre
      @centre = Centre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centre_params
      params.require(:centre).permit(:name, :address, :city, :province, :url, :description, :phone, :email, :latitude, :longitude)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to centres_path, notice: "Welcome back, #{user.firstname}!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :back, notice: "See you soon!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to centres_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/centres/_form.html.erb
<%= form_for(@centre) do |f| %>
  <% if @centre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@centre.errors.count, "error") %> prohibited this centre from being saved:</h2>

      <ul>
      <% @centre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/centres/edit.html.erb
<h1>Editing centre</h1>

<%= render 'form' %>

<%= link_to 'Show', @centre %> |
<%= link_to 'Back', centres_path %>

app/views/centres/index.html.erb
<div id="map-canvas"></div> <!-- Google Maps -->
<!-- Content -->
<div class="container-fluid" id="main">
  <div class="row">
    <div class="col-xs-8" id="left">

        <% @centres.group_by_city.each do |city, centres| %>
          <ul id="city-name-list-header"> <%= city %></ul>
            <% centres.each do |centre| %>
              <li class="community-centre-list-item"><%= centre.name %> - <%= centre.address %></li>
            <% end %>
          </ul>
        <% end %>
        
      <br>
      <% if current_user %>
        <%= link_to 'New Centre', new_centre_path %>
      <% end %>

    </div>
  </div>
</div> <!-- /Content -->

app/views/centres/new.html.erb
<% if current_user %>
  <h1>New centre</h1>

  <%= render 'form' %>

  <%= link_to 'Back', centres_path %>
<% end %>

app/views/centres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @centre.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @centre.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @centre.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @centre.province %>
</p>

<p>
  <strong>Url:</strong>
  <%= @centre.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @centre.description %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @centre.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @centre.email %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @centre.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @centre.longitude %>
</p>

<%= link_to 'Edit', edit_centre_path(@centre) %> |
<%= link_to 'Back', centres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metro Vancouver Community Centres</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if impersonating_user? %> 
    <p><%= link_to 'Switch back to account', admin_user_stop_impersonating_path(session[:user_id]), method: :get %></p>
  <% end %> 
  <div class="container-fluid">
    <!--Navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home"></span> Metro Vancouver Community Centres</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li id="logged-user">
                Signed in as <%= current_user.full_name %>
              </li> 
              <li>
                <button type="button" class="btn btn-default navbar-btn" id="btn-login" id="btn-login"><%= link_to "Log out", session_path("current"), method: :delete %></button>
              </li>
            <% else %>
              <li>
                <button type="button" class="btn btn-default navbar-btn" id="btn-login"><%= link_to 'Login', new_session_path %></button>
              </li>
              <li>
                <button type="button" class="btn btn-default navbar-btn" id="btn-sign-up"><%= link_to "Sign Up", new_user_path %></button>
              </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div> <!-- Container -->
    </nav> <!-- / Navbar -->
  </div>
  
  <!-- Show Error Messages -->
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>

  <div class="container-fluid">
    <%= yield %>
  </div>   
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.20&key=AIzaSyBkyaNI92nJvwe2eZMnrcsO4GTJDEUmal0"></script>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<h1>User Profile</h1>
<p><%= @user.full_name %></p>
<p><%= @user.email %></p>
<!-- <% unless @user.reviews.empty? %>
  <hr>
  <h2>Your movie reviews</h2>
  <% @user.reviews.each do |review| %>
    <p><%= link_to review.movie.title, movie_path(review.movie) %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <p><%= review.text %></p>
  <% end %>
<% end %> -->